displayName=Raid Data Tracker
author=Raitab
support=https://github.com/Raitab/raid-data-tracker/tree/raid-data-tracker
description=Tracks all loot received within raids. Also tracks the total and personal points received so that you can accurately determine your personal droprate and dryness.
tags=tracker,raid tracker,raid data,raid data tracker,raids,raid,cox,chambers,xeric,theatre,blood,tob,tombs,amascut,toa
plugins=com.raidtracker.RaidTrackerPlugin